// <auto-generated />
namespace Fitness.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SomeFixes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeFixes1));
        
        string IMigrationMetadata.Id
        {
            get { return "202012271119257_SomeFixes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
